/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;



/**
 *
 * @author ALUMNO
 */
public class jfrmlogin extends javax.swing.JFrame {

 private Timer tiempo;
 int cont;
 public final static int TWO_SECOND=50;
    
   
    public jfrmlogin() {
        initComponents();
        
    setLocationRelativeTo(null); //ubicacion de la pantalla
    
    jpbinicio.setVisible(false);    
        
    }
    
  class TimerListener implements ActionListener  {
      
      public void actionPerformed(ActionEvent e){
          
        cont ++;
        jpbinicio.setValue(cont);
        if(cont==100){
            tiempo.stop();
            principal.jfrminicio menu=new principal.jfrminicio ();
            menu.setVisible(true);
            setVisible(false);
        }
      }
  }
    public void  esconder(){this.setVisible(false);}
     
        public void activar(){tiempo.start();
    }
        
        
    public void iniciosesion(){
        String usuario =jtxtusuario.getText();
         String contra =String .valueOf(jtxtclave.getPassword());
         if(usuario.equals("erick")&& contra.compareTo("erick")==0){
        jpbinicio.setVisible(true);
        cont=-1;
        jpbinicio.setValue(0);
        jpbinicio.setStringPainted(true);
        tiempo=new Timer (TWO_SECOND, new TimerListener());
        activar();
        
    }else{
             JOptionPane.showMessageDialog(null, "Error al ingresar usuario y contraseña");
         }
         
                 }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtusuario = new javax.swing.JTextField();
        jbtnok = new javax.swing.JButton();
        jbtnclave = new javax.swing.JButton();
        jpbinicio = new javax.swing.JProgressBar();
        jtxtclave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(515, 340));
        setMinimumSize(new java.awt.Dimension(515, 340));
        setPreferredSize(new java.awt.Dimension(515, 340));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(229, 97, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("CONTRASEÑA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(231, 135, 80, 15);

        jtxtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtusuario);
        jtxtusuario.setBounds(325, 84, 140, 30);

        jbtnok.setText("INGRESAR");
        jbtnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnokActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnok);
        jbtnok.setBounds(232, 190, 100, 40);

        jbtnclave.setText("CANCELAR");
        jbtnclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnclave);
        jbtnclave.setBounds(354, 190, 100, 40);

        jpbinicio.setBackground(new java.awt.Color(0, 255, 255));
        jpbinicio.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(jpbinicio);
        jpbinicio.setBounds(30, 280, 444, 10);

        jtxtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtclaveActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtclave);
        jtxtclave.setBounds(325, 132, 140, 30);

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("SISTEMA DEL COLEGIO ANGELES DE DIOS ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(7, 24, 530, 21);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/imagenes/manos-en-el-cielo-dios-y-hombre-fondo-500x313.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclaveActionPerformed
 
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnclaveActionPerformed

    private void jbtnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnokActionPerformed
        // TODO add your handling code here:
        
        iniciosesion();
        
        
    }//GEN-LAST:event_jbtnokActionPerformed

    private void jtxtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtusuarioActionPerformed

    private void jtxtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtclaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmlogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnclave;
    private javax.swing.JButton jbtnok;
    private javax.swing.JProgressBar jpbinicio;
    private javax.swing.JPasswordField jtxtclave;
    private javax.swing.JTextField jtxtusuario;
    // End of variables declaration//GEN-END:variables
}
